services:
  # Django Backend Service
  backend:
    image: mehtameet2802/manager:latest
    container_name: manager_backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"