# Generated by Django 5.1.7 on 2025-03-19 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_required', models.BooleanField(default=False)),
                ('item_cost', models.IntegerField()),
                ('item_stock', models.IntegerField()),
                ('min_quantity', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_cost', models.IntegerField()),
                ('transaction_date_time', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=10)),
                ('transaction_units', models.IntegerField()),
                ('final_stock', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.user')),
            ],
        ),
    ]
